spring:
  application:
    name: befit
  h2:
    console:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
